$(document).ready(function(){

      $("#cit1").click(function(){
         $('.cita').show(100);

         $("#cit1_1").css({"opacity" : "1", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit01").css({"opacity" : "1", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit2").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit02").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit3").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit03").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit4_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit04").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit5_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit05").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit6_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit06").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit7_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit07").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit8_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit08").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit9_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit09").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit10_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit10").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit11_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit11").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
          });

      $("#cit2").click(function(){
         $('.cita').show(100);
         $("#cit1_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit01").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit2").css({"opacity" : "1", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit02").css({"opacity" : "1", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit3").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit03").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit4_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit04").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit5_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit05").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit6_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit06").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit7_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit07").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit8_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit08").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit9_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit09").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit10_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit10").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit11_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit11").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
          });

      $("#cit3").click(function(){
         $('.cita').show(100);
         $("#cit1_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit01").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit2").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit02").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit3").css({"opacity" : "1", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit03").css({"opacity" : "1", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit4_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit04").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit5_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit05").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit6_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit06").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit7_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit07").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit8_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit08").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit9_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit09").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit10_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit10").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit11_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit11").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
          });

      $("#cit4").click(function(){
         $('.cita').show(100);
         $("#cit1_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit01").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit2").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit02").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit3").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit03").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit4_1").css({"opacity" : "1", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit04").css({"opacity" : "1", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit5_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit05").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit6_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit06").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit7_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit07").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit8_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit08").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit9_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit09").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit10_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit10").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit11_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit11").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
          });

      $("#cit5").click(function(){
         $('.cita').show(100);
         $("#cit1_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit01").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit2").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit02").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit3").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit03").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit4_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit04").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit5_1").css({"opacity" : "1", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit05").css({"opacity" : "1", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit6_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit06").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit7_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit07").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit8_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit08").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit9_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit09").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit10_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit10").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit11_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit11").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
          });

      $("#cit6").click(function(){
         $('.cita').show(100);
         $("#cit1_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit01").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit2").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit02").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit3").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit03").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit4_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit04").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit5_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit05").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit6_1").css({"opacity" : "1", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit06").css({"opacity" : "1", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit7_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit07").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit8_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit08").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit9_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit09").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit10_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit10").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit11_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit11").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
          });


      $("#cit7").click(function(){
         $('.cita').show(100);
         $("#cit1_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit01").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit2").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit02").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit3").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit03").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit4_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit04").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit5_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit05").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit6_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit06").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit7_1").css({"opacity" : "1", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit07").css({"opacity" : "1", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit8_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit08").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit9_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit09").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit10_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit10").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit11_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit11").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
          });

      $("#cit8").click(function(){
         $('.cita').show(100);
         $("#cit1_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit01").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit2").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit02").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit3").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit03").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit4_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit04").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit5_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit05").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit6_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit06").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit7_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit07").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit8_1").css({"opacity" : "1", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit08").css({"opacity" : "1", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit9_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit09").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit10_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit10").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit11_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit11").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
          });

      $("#cit9").click(function(){
         $('.cita').show(100);
         $("#cit1_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit01").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit2").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit02").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit3").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit03").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit4_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit04").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit5_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit05").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit6_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit06").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit7_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit07").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit8_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit08").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit9_1").css({"opacity" : "1", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit09").css({"opacity" : "1", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit10_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit10").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit11_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit11").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
          });

      $("#cit10").click(function(){
         $('.cita').show(100);
         $("#cit1_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit01").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit2").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit02").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit3").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit03").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit4_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit04").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit5_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit05").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit6_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit06").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit7_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit07").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit8_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit08").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit9_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit09").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit10_1").css({"opacity" : "1", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit10").css({"opacity" : "1", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit11_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit11").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
          });

      $("#cit11").click(function(){
         $('.cita').show(100);
         $("#cit1_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit01").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit2").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit02").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit3").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit03").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit4_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit04").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit5_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit05").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit6_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit06").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit7_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit07").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit8_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit08").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit9_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit09").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit10_1").css({"opacity" : "0.3", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit10").css({"opacity" : "0", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#cit11_1").css({"opacity" : "1", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
         $("#Cit11").css({"opacity" : "1", "-webkit-transition" : "opacity 0.1s ease-in", "-moz-transition" : "opacity 0.1s ease-in", "-ms-transition" : "opacity 0.1s ease-in", "transition" : "opacity 0.1s ease-in" });
          });

 });	